"""HTTP I/O against Supabase Storage signed URLs.

Worker downloads audio with a signed-download URL, uploads results with a signed-upload
URL. Both URLs are generated by the API server before dispatch, and they're tenant-scoped
under `<tenant_uuid>/...`. The worker never holds a Supabase service key.
"""

from __future__ import annotations

import os
import tempfile
from pathlib import Path

import httpx

_TIMEOUT = httpx.Timeout(60.0, connect=10.0)


def download_to_temp(url: str) -> str:
    """Stream a remote audio file to a private temp path. Caller is responsible for cleanup."""
    suffix = _extract_suffix(url)
    fd, path = tempfile.mkstemp(suffix=suffix)
    os.close(fd)
    with httpx.stream("GET", url, timeout=_TIMEOUT) as resp:
        resp.raise_for_status()
        with open(path, "wb") as f:
            for chunk in resp.iter_bytes(chunk_size=64 * 1024):
                if chunk:
                    f.write(chunk)
    # Tighten permissions — mkstemp already uses 0600 but be explicit on shared workers.
    Path(path).chmod(0o600)
    return path


def upload_audio(signed_upload_url: str, payload: bytes, *, content_type: str) -> None:
    """PUT the generated audio to the pre-signed URL Supabase issued for this tenant."""
    with httpx.Client(timeout=_TIMEOUT) as client:
        resp = client.put(
            signed_upload_url,
            content=payload,
            headers={"Content-Type": content_type, "x-upsert": "true"},
        )
        resp.raise_for_status()


def _extract_suffix(url: str) -> str:
    # Best effort — strip query string, take the last extension if any.
    path = url.split("?", 1)[0]
    for ext in (".wav", ".mp3", ".opus", ".ogg", ".webm", ".m4a"):
        if path.endswith(ext):
            return ext
    return ".bin"
